/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnTrackIdRouteImport } from './routes/learn.$trackId'
import { Route as LearnTrackIdIndexRouteImport } from './routes/learn.$trackId.index'
import { Route as LearnTrackIdLessonIdRouteImport } from './routes/learn.$trackId.$lessonId'

const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const LearnTrackIdRoute = LearnTrackIdRouteImport.update({
  id: '/$trackId',
  path: '/$trackId',
  getParentRoute: () => LearnRoute,
} as any)
const LearnTrackIdIndexRoute = LearnTrackIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnTrackIdRoute,
} as any)
const LearnTrackIdLessonIdRoute = LearnTrackIdLessonIdRouteImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => LearnTrackIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/learn': typeof LearnRouteWithChildren
  '/profile': typeof ProfileRoute
  '/roadmap': typeof RoadmapRoute
  '/learn/$trackId': typeof LearnTrackIdRouteWithChildren
  '/learn/': typeof LearnIndexRoute
  '/learn/$trackId/$lessonId': typeof LearnTrackIdLessonIdRoute
  '/learn/$trackId/': typeof LearnTrackIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/roadmap': typeof RoadmapRoute
  '/learn': typeof LearnIndexRoute
  '/learn/$trackId/$lessonId': typeof LearnTrackIdLessonIdRoute
  '/learn/$trackId': typeof LearnTrackIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/learn': typeof LearnRouteWithChildren
  '/profile': typeof ProfileRoute
  '/roadmap': typeof RoadmapRoute
  '/learn/$trackId': typeof LearnTrackIdRouteWithChildren
  '/learn/': typeof LearnIndexRoute
  '/learn/$trackId/$lessonId': typeof LearnTrackIdLessonIdRoute
  '/learn/$trackId/': typeof LearnTrackIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/learn'
    | '/profile'
    | '/roadmap'
    | '/learn/$trackId'
    | '/learn/'
    | '/learn/$trackId/$lessonId'
    | '/learn/$trackId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/profile'
    | '/roadmap'
    | '/learn'
    | '/learn/$trackId/$lessonId'
    | '/learn/$trackId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/learn'
    | '/profile'
    | '/roadmap'
    | '/learn/$trackId'
    | '/learn/'
    | '/learn/$trackId/$lessonId'
    | '/learn/$trackId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  LearnRoute: typeof LearnRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RoadmapRoute: typeof RoadmapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/$trackId': {
      id: '/learn/$trackId'
      path: '/$trackId'
      fullPath: '/learn/$trackId'
      preLoaderRoute: typeof LearnTrackIdRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/$trackId/': {
      id: '/learn/$trackId/'
      path: '/'
      fullPath: '/learn/$trackId/'
      preLoaderRoute: typeof LearnTrackIdIndexRouteImport
      parentRoute: typeof LearnTrackIdRoute
    }
    '/learn/$trackId/$lessonId': {
      id: '/learn/$trackId/$lessonId'
      path: '/$lessonId'
      fullPath: '/learn/$trackId/$lessonId'
      preLoaderRoute: typeof LearnTrackIdLessonIdRouteImport
      parentRoute: typeof LearnTrackIdRoute
    }
  }
}

interface LearnTrackIdRouteChildren {
  LearnTrackIdLessonIdRoute: typeof LearnTrackIdLessonIdRoute
  LearnTrackIdIndexRoute: typeof LearnTrackIdIndexRoute
}

const LearnTrackIdRouteChildren: LearnTrackIdRouteChildren = {
  LearnTrackIdLessonIdRoute: LearnTrackIdLessonIdRoute,
  LearnTrackIdIndexRoute: LearnTrackIdIndexRoute,
}

const LearnTrackIdRouteWithChildren = LearnTrackIdRoute._addFileChildren(
  LearnTrackIdRouteChildren,
)

interface LearnRouteChildren {
  LearnTrackIdRoute: typeof LearnTrackIdRouteWithChildren
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnTrackIdRoute: LearnTrackIdRouteWithChildren,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  LearnRoute: LearnRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RoadmapRoute: RoadmapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
